name: GuildedVault
version: '1.0-SNAPSHOT'
main: net.gildedgoobers.gildedvault.core.GildedVault
api-version: '1.21'
authors: [GildedGoobers]
description: A tip of the hat to the original Vault plugin, but for PaperMC and better.
website: https://github.com/gildedgoobers
